### ISSUE TITLE
Would this work for the R2 Gen 2 as well?

### ISSUE THREAD

**Issue by ManoharOfficial** [SuperTaiyaki/hiby-firmware-tools#5]
I was wondering if this tool works for the R2 Gen 2 as well? Seeing as both the players use the X1000E and the update zips also are very similar/identical.
I would very much like to modify some default system graphics elements and a few icons here and there.

**Comment by ManoharOfficial** [comment]
UPDATE: I just found out that HiBy provides the firmware for Shanling and other players as well. AND shanling already has a published, unpacking and re-packing tool with instructions. 
I just unpacked the R2 ii firmware and everything seems identical/logical to Shanling theme editing steps. 
For my use case this is more than enough as I won't be touching any code, just GUI elements (which just seem to be images. Even the clock is just couple of images on the r2ii lol)
Here's the tool link: https://www.head-fi.org/threads/shanling-daps-user-theme.866314/ 
I still have to try repacking and flashing the player tho... that is what is making me nervous lol

**Comment by ManoharOfficial** [comment]
closed

**Comment by SuperTaiyaki** [comment]
Heh, I was going to mention that but you beat me to it.

I don't have an R2 to check but the R3 has a recovery mode. If there's a firmware file on the SD card and it's started while holding a certain button, it goes straight to the flasher so in theory it should be possible to recover a bad flash. To maximize chances of recovery I would get the recovery procedure working using official firmware, and then experiment with the update reduced to only the system partition.

**Comment by ManoharOfficial** [comment]
r2ii seems to have similar recovery options/functionality, according to hiby's spokesperson : https://www.head-fi.org/threads/latest-instructions-for-x-player-firmware-diying.764722/#post-17766895
